version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - golang.org/x/sys/unix
            - golang.org/x/crypto/sha3
            - golang.org/x/crypto/argon2
            - github.com/oasisprotocol
            - github.com/btcsuite/btcd
            - github.com/adrg/xdg
            - github.com/AlecAivazis/survey/v2
            - github.com/ethereum/go-ethereum
            - github.com/miguelmota/go-ethereum-hdwallet
            - github.com/mitchellh/mapstructure
            - github.com/olekukonko/tablewriter
            - github.com/spf13/cobra
            - github.com/spf13/pflag
            - github.com/spf13/viper
            - github.com/stretchr/testify
            - github.com/tyler-smith/go-bip39
            - github.com/zondax/ledger-go
            - github.com/foxboron/go-uefi/authenticode
            - golang.org/x/text
            - gopkg.in/yaml.v3
            - github.com/compose-spec/compose-go/v2
            - github.com/github/go-spdx/v2
            - github.com/opencontainers/image-spec/specs-go/v1
            - oras.land/oras-go/v2
            - github.com/wI2L/jsondiff
            - github.com/google/uuid
            - golang.org/x/net/idna
            - golang.org/x/term
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
            - pkg: github.com/fxamacker/cbor/v2
              desc: Use oasis-core/go/common/cbor instead
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: "/common/"
        text: "var-naming: avoid meaningless package names"
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofumpt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/oasisprotocol/cli

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
