# golangci-lint configuration.

# For more information, see:
# https://golangci-lint.run/usage/configuration/.

run:
  timeout: 5m

linters:
  # Disable all linters except the ones explicitly listed below.
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - goheader
    - goimports
    - revive
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - stylecheck
    - sqlclosecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
        allow:
          - $gostd
          - github.com/oasisprotocol
          - github.com/btcsuite/btcd
          - github.com/adrg/xdg
          - github.com/AlecAivazis/survey/v2
          - github.com/ethereum/go-ethereum
          - github.com/miguelmota/go-ethereum-hdwallet
          - github.com/mitchellh/mapstructure
          - github.com/olekukonko/tablewriter
          - github.com/spf13/cobra
          - github.com/spf13/pflag
          - github.com/spf13/viper
          - github.com/stretchr/testify
          - github.com/tyler-smith/go-bip39
          - github.com/zondax/ledger-go
          - github.com/foxboron/go-uefi/authenticode
          - golang.org/x/text
          - gopkg.in/yaml.v3
          - github.com/compose-spec/compose-go/v2
          - github.com/github/go-spdx/v2
  exhaustive:
    # Switch statements are to be considered exhaustive if a 'default' case is
    # present, even if all enum members aren't listed in the switch.
    default-signifies-exhaustive: true
  govet:
    # Enabled checking for shadowed variables.
    check-shadowing: true
