project_name: Oasis CLI

before:
  hooks:
    - go mod tidy

universal_binaries:
  - id: oasis-darwin-universal
    ids:
      - oasis-darwin-amd64
      - oasis-darwin-arm64
    replace: true
    name_template: oasis

env:
  - CGO_ENABLED=1

builds:
  - &build-common
    id: oasis-linux-amd64
    binary: oasis
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -buildid=
      - "{{.Env.GOLDFLAGS_VERSION}}"
  - <<: *build-common
    id: oasis-linux-arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
  - <<: *build-common
    id: oasis-darwin-amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
  - <<: *build-common
    id: oasis-darwin-arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
  - <<: *build-common
    id: oasis-windows-amd64
    binary: oasis
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64

archives:
  - name_template: "{{replace .ProjectName \" \" \"_\" | tolower}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    wrap_in_directory: true
    builds:
      - oasis-linux-amd64
      - oasis-linux-arm64
      - oasis-darwin-universal
      - oasis-windows-amd64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
  groups:
    - title: Breaking changes
      regexp: "^.*breaks[(\\w)]*:+.*$"
      order: 0
    - title: New Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 5
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Dependencies updates
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 500
    - title: Other changes
      order: 999

release:
  name_template: "{{.ProjectName}} {{.Version}}"

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1.
  prerelease: auto

  footer: |
    **Full Changelog**: https://github.com/oasisprotocol/cli/compare/{{ .PreviousTag }}...{{ .Tag }}
