name: Brew audit & test
on: [push, pull_request]

jobs:
  audit:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - name: Audit
        run: brew audit --strict --online --formula Formula/oasis.rb
      - name: Build & test
        run: |
          brew install --build-from-source Formula/oasis.rb
          oasis --version